server:
  port: 8081
spring:
  application:
    name: integral-dingtalk-provider
  rabbitmq:
    host: 192.168.226.132
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:mysql://Lenovo:3306/mybatis?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    application:
      name: item-service #将来会作为微服务的名称
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.dingtalk.item.pojo
testcontent: cuixiaohong
