spring:
  datasource:
    url: jdbc:mysql://121.122.212.212:3306/leyou?serverTimezone=UTC # 连自己的数据库即可
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: producer-service
  rabbitmq:
    host: 192.168.226.132
    username: guest
    password: guest
    virtual-host: /
mybatis:
  type-aliases-package: com.eureka.producerdemo.pojo
eureka:
  client:
    register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: true # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 90 # 服务失效时间，默认值90秒（90秒即过期）
    lease-renewal-interval-in-seconds: 30 # 服务续约(renew)的间隔，默认为30秒（也就是30秒一次心跳）
    instance-id: ${spring.application.name}:${server.port} # 修改Eureka的Status一列的构成
ip: 777.888.999.66666
